#!/bin/bash

glidein_config="$1"

function info {
    echo "INFO  " $@ 1>&2
}

function warn {
    echo "WARN  " $@ 1>&2
}

###########################################################
# import add_config_line and add_condor_vars_line functions

add_config_line_source=`grep '^ADD_CONFIG_LINE_SOURCE ' $glidein_config | awk '{print $2}'`
source $add_config_line_source

# Patch over add_config_line() with a safer version
add_config_line() {
    # Ignore the call if the exact config line is already in there
    if ! grep -q "^${*}$" "${glidein_config}"; then
        # Use temporary files to make sure multiple add_config_line() calls don't clobber
        # the glidein_config.
        local r="$(head -c16 /dev/urandom | base64 -w0 - | tr / _)"
        local tmp_config1="${glidein_config}.$r.1"
        local tmp_config2="${glidein_config}.$r.2"

        # Copy the glidein config so it doesn't get modified while we grep out the old value
        if ! cp -p "${glidein_config}" "${tmp_config1}"; then
            warn "Error writing ${tmp_config1}"
            rm -f "${tmp_config1}"
            exit 1
        fi
        grep -v "^$1 " "${tmp_config1}" > "${tmp_config2}"
        rm -f "${tmp_config1}"
        if [ ! -f "${tmp_config2}" ]; then
            warn "Error creating ${tmp_config2}"
            exit 1
        fi
        # NOTE that parameters are flattened if not quoted, if there are blanks they are separated by single space
        echo "$@" >> "${tmp_config2}"

        # Replace glidein config atomically
        if ! mv -f "${tmp_config2}" "${glidein_config}"; then
            warn "Error updating ${glidein_config} from ${tmp_config2}"
            rm -f "${tmp_config2}"
            exit 1
        fi
    fi
}
# End add_config_line() patch

condor_vars_file=`grep -i "^CONDOR_VARS_FILE " $glidein_config | awk '{print $2}'`

###########################################################
# stashcp 
STASHCP=$PWD/client/stashcp
STASHCP_DEBUG="-d"
STASHCP_TEST_FILE="/ospool/uc-shared/public/OSG-Staff/validation/test.txt"
STASH_PLUGIN=$PWD/client/stash_plugin
chmod 755 $STASHCP $STASH_PLUGIN

TIMEOUT=$(which timeout 2>/dev/null)
if [ "x$TIMEOUT" != "x" ]; then
    TIMEOUT="$TIMEOUT 120s"
fi

# The bash builtin time is no good because it pollutes
# stderr with hardcoded real, sys, and user lines.
TIME=$(which time 2>/dev/null)
if [ "x$TIME" != "x" ]; then
    # Without --quiet, newer versions of TIME(1)
    # will prepend an extra line to the output
    # if the process exits with a non-zero exit code.
    # Therefore, we use $(tail -1 stashcp-test.time)
    # below to get the runtime of stashcp.
    TIME="$TIME --output=stashcp-test.time --format=%e"
fi

glidein_site=`grep -i "^GLIDEIN_Site " $glidein_config | awk '{print $2}'`
if [[ -z $OSG_SITE_NAME ]]; then
    OSG_SITE_NAME=$glidein_site
fi

# also run a simple test (TODO: make this IGWN-specific)
info "Testing $STASHCP $STASHCP_DEBUG $STASHCP_TEST_FILE..."
if $TIME $TIMEOUT $STASHCP $STASHCP_DEBUG $STASHCP_TEST_FILE stashcp-test.file >> stashcp-test.log 2>&1; then
    if [ -f stashcp-test.time ]; then
        info "Succeeded (in $(tail -1 stashcp-test.time)s)!"
    else
        info "Succeeded!"
    fi
    add_config_line FILETRANSFER_PLUGINS "\$(FILETRANSFER_PLUGINS),$STASH_PLUGIN"
    add_condor_vars_line FILETRANSFER_PLUGINS "C" "-" "+" "N" "N" "-"
else
    if [ "$?" -eq "124" ]; then
        warn "Failed (timed out after 120s)! stashcp output:"
    elif [ -f stashcp-test.time ]; then
        warn "Failed (in $(tail -1 stashcp-test.time)s)! stashcp output:"
    else
        warn "Failed! stashcp output:"
    fi
    while read line; do warn "$line"; done < stashcp-test.log
fi

echo "All done (igwn-additional-htcondor-config)"
