#!/bin/bash                                                                                                         
                                                                                                                    
glidein_config="$1"                                                                                                 

###########################################################
# import add_config_line and add_condor_vars_line functions

add_config_line_source=`grep '^ADD_CONFIG_LINE_SOURCE ' $glidein_config | awk '{print $2}'`
source $add_config_line_source

condor_vars_file=`grep -i "^CONDOR_VARS_FILE " $glidein_config | awk '{print $2}'`

###########################################################

###########################################################
# gpus - only for the GPU group

if [ "$glidein_config" != "NONE" ]; then
    group=`grep '^GLIDECLIENT_Group ' $glidein_config | awk '{print $2}'`
    if [ "x$group" = "xgpu" ]; then
        wget -nv http://osg-flock.grid.iu.edu/gwms-extras/condor_gpu_discovery
        chmod 755 condor_gpu_discovery
    fi
    add_config_line SLOT_TYPE_1 "cpus=\$(GLIDEIN_CPUS), gpus=1"
    add_condor_vars_line SLOT_TYPE_1 "C" "-" "+" "N" "N" "-"
fi

###########################################################
# stashcp - only use if oasis is available
if [ -e /cvmfs/oasis.opensciencegrid.org/. ]; then
    cat >stashcp_plugin <<EOF
#!/bin/bash

if [ "x\$1" = "x-classad" ]; then
   echo "PluginVersion = \"0.1\""
   echo "PluginType = \"FileTransfer\""
   echo "SupportedMethods = \"stash\""

   exit 0
fi

FULLSRC=\$1
LOC=\$2
SRC=\$(echo \$FULLSRC | cut -d':' -f2-)
. /cvmfs/oasis.opensciencegrid.org/osg/modules/lmod/current/init/bash
module load stashcp
module load xrootd
stashcp -r -s \$SRC -l \$LOC > /dev/null 2>&1

EOF
    chmod 755 stashcp_plugin
    add_config_line FILETRANSFER_PLUGINS "\$(FILETRANSFER_PLUGINS),$PWD/stashcp_plugin"
    add_condor_vars_line FILETRANSFER_PLUGINS "C" "-" "+" "N" "N" "-"
fi


