#!/bin/bash


function my_info
{
    echo "INFO:    $1"
}

function my_warn
{
    echo "WARNING: $1"
}

function my_error
{
    echo "FATAL ERROR: $1"
    exit 1
}


my_info "This is an OSG-FLOCK node validation script."
my_info "In case of problems, contact Mats Rynge (rynge@isi.edu)"

my_info "CWD is $PWD"

if ! (cd $PWD && ls) >/dev/null; then
    my_error "PWD points to a non-existent directory"
fi

my_info "Checking disk space - 1 GB free is required"
disk_required=1000000
free=`df -kP . | awk '{if (NR==2) print $4}'`
free_gb=$(($free / 1024 / 1024))
my_info "   ...  $free_gb GB space available"
if [ "x$free" == "x" -o $free -lt $disk_required ]; then
    my_error "The workdir does not have enough available diskspace"
fi

my_info "Checking the environment..."

my_info "   checking PATH ($PATH)"
if ! (echo "$PATH" | grep /usr/bin) >/dev/null 2>&1; then
    my_warn "The PATH does not have /usr/bin"
fi

my_info "   checking access to /usr/bin/"
if ! (/bin/ls -l /usr/bin/) >/dev/null 2>&1; then
    my_error "Simple ls of /usr/bin/ did not work"
fi

my_info "   checking for globus-url-copy"
if ! (globus-url-copy -version 2>&1 | grep ^globus-url-copy:) >/dev/null 2>&1; then
    my_warn "globus-url-copy not found - this usually means that the wn package is not installed"
fi

my_info "Node looks good - exiting with 0"
exit 0

