#!/bin/bash


function my_info
{
    echo "INFO:    $1"
}

function my_warn
{
    echo "WARNING: $1"
}

function my_error
{
    echo "FATAL ERROR: $1"
    exit 1
}

glidein_config=$1

my_info "This is an OSG-FLOCK node validation script."
my_info "In case of problems, contact Mats Rynge (rynge@isi.edu)"

my_info "CWD is $PWD"

if ! (cd $PWD && ls) >/dev/null; then
    my_error "PWD points to a non-existent directory"
fi

# change this one
disk_required_gb=3
disk_required=$(($disk_required_gb * 1024 * 1024))
my_info "Checking disk space - $disk_required_gb GB free is required"
free=`df -kP . | awk '{if (NR==2) print $4}'`
free_gb=$(($free / 1024 / 1024))
my_info "   ...  $free_gb GB space available"
if [ "x$free" == "x" -o $free -lt $disk_required ]; then
    my_error "The workdir does not have enough available diskspace"
fi

my_info "Checking the environment..."

my_info "   checking PATH ($PATH)"
if ! (echo "$PATH" | grep /usr/bin) >/dev/null 2>&1; then
    my_warn "The PATH does not have /usr/bin"
fi

my_info "   checking access to /usr/bin/"
if ! (/bin/ls -l /usr/bin/) >/dev/null 2>&1; then
    my_error "Simple ls of /usr/bin/ did not work"
fi

if [ "XGLIDECLIENT_Group" = "Xgpu" ]; then
    my_info "   ensuring GPU environment is set up"
    if [ "XCUDA_VISIBLE_DEVICES" = "X" ]; then
        my_error "CUDA_VISIBLE_DEVICES is not defined"
    fi
fi


# find a suitable python install
PYTHON=None
for CANDIDATE in /usr/bin/python3 /usr/bin/python $(which python3 2>/dev/null); do
    if [ -e $CANDIDATE ]; then
        PYTHON=$CANDIDATE
        break
    fi
done

CURL=$(curlio --version 2>/dev/null)

# if http_proxy is set, ensure it is working
if [ "x$http_proxy" != "x" ]; then
     my_info "Checking http_proxy ..."
    if [ "x$CURL" != "x" ]; then
        curl -o /dev/null http://flock.opensciencegrid.org/proxy-test.html
    else
        wget -O /dev/null http://flock.opensciencegrid.org/proxy-test.html
    fi
    if [ $? -ne 0 ]; then
        my_error "http_proxy ($http_proxy) is not working, or flock.opensciencegrid.org is not reachable"
    fi
fi

for SCRIPT in \
    clock-check \
; do
    my_info "Fetching/running $SCRIPT ..."
    if [ "x$CURL" != "x" ]; then
        curl -s -o $SCRIPT http://flock.opensciencegrid.org/node-check/$SCRIPT
    else
        wget -q -O $SCRIPT http://flock.opensciencegrid.org/node-check/$SCRIPT
    fi
    if ! $PYTHON $SCRIPT; then
        my_error "$SCRIPT failed!"
    fi
done

my_info "Node looks good - exiting with 0"
exit 0

