#!/bin/bash                                                                                                         
                                                                                                                    
glidein_config="$1"                                                                                                 

###########################################################
# import add_config_line and add_condor_vars_line functions

add_config_line_source=`grep '^ADD_CONFIG_LINE_SOURCE ' $glidein_config | awk '{print $2}'`
source $add_config_line_source

condor_vars_file=`grep -i "^CONDOR_VARS_FILE " $glidein_config | awk '{print $2}'`

###########################################################


# stashcp - only use if oasis is available
if [ -e /cvmfs/oasis.opensciencegrid.org/. ]; then
    chmod 755 client/stashcp_plugin
    add_config_line FILETRANSFER_PLUGINS "\$(FILETRANSFER_PLUGINS),$PWD/client/stashcp_plugin"
    add_condor_vars_line FILETRANSFER_PLUGINS "C" "-" "+" "N" "N" "-"
fi


