#!/bin/bash


function my_info
{
    echo "INFO:    $1"
}

function my_warn
{
    echo "WARNING: $1"
}

function my_error
{
    echo "FATAL ERROR: $1"
    exit 1
}

glidein_config=$1

my_info "This is an OSPool node validation script."
my_info "In case of problems, contact Mats Rynge (rynge@isi.edu)"

my_info "CWD is $PWD"

if ! (cd $PWD && ls) >/dev/null; then
    my_error "PWD points to a non-existent directory"
fi

# provide some details about the IDTOKEN
TS=$(date +'%s')
my_info "List of IDTOKENs (current ts is $TS):"
./main/condor/bin/condor_token_list -dir ticket/ 2>&1

# change this one
disk_required_gb=5
disk_required=$(($disk_required_gb * 1024 * 1024))
my_info "Checking disk space - $disk_required_gb GB free is required"
free=`df -kP . | awk '{if (NR==2) print $4}'`
free_gb=$(($free / 1024 / 1024))
my_info "   ...  $free_gb GB space available"
if [ "x$free" == "x" -o $free -lt $disk_required ]; then
    my_error "The workdir does not have enough available diskspace"
fi

my_info "Checking the environment..."

my_info "   checking PATH ($PATH)"
if ! (echo "$PATH" | grep /usr/bin) >/dev/null 2>&1; then
    my_warn "The PATH does not have /usr/bin"
fi

my_info "   checking access to /usr/bin/"
if ! (/bin/ls -l /usr/bin/) >/dev/null 2>&1; then
    my_error "Simple ls of /usr/bin/ did not work"
fi

if [ "XGLIDECLIENT_Group" = "Xgpu" ]; then
    my_info "   ensuring GPU environment is set up"
    if [ "XCUDA_VISIBLE_DEVICES" = "X" ]; then
        my_error "CUDA_VISIBLE_DEVICES is not defined"
    fi
fi

# quick check for curl - this is not a hard requirement, but used in
# many places like HTCondor file transfers and stashcp
CURL=$(which curl 2>/dev/null)
if [[ "x$CURL" = "x" ]]; then
    my_warn "curl is not available"
else
    CURL_VERSION=$(curl --version | head -n 1)
    my_info "curl is available: $CURL_VERSION"
fi

# if http_proxy is set, ensure it is working
if [ "x$http_proxy" != "x" ]; then
    my_info "Checking http_proxy ..."
    if [ "x$CURL" != "x" ]; then
        curl -o /dev/null https://ospool-fe.osg.chtc.io/vofrontend/monitor/frontendStatus.html
    else
        wget -O /dev/null https://ospool-fe.osg.chtc.io/vofrontend/monitor/frontendStatus.html
    fi
    if [ $? -ne 0 ]; then
        my_error "http_proxy ($http_proxy) is not working, or ospool-fe.osg.chtc.io is not reachable"
    fi
fi

my_info "Node looks good - exiting with 0"
exit 0

