#!/bin/bash
#
# This script is run *once* after the GWMS Singularity detection,
# and can be used to do additional Singularity capability testing
# and advertising.
#

glidein_config="$1"
export glidein_config

function info {
    echo "INFO  " $@ 1>&2
}

function my_warn {
    echo "WARN  " $@ 1>&2
    export GLIDEIN_VALIDATION_WARNINGS="$@. $GLIDEIN_VALIDATION_WARNINGS"
}

function get_glidein_config_value {
    # extracts a config attribute value from 
    # $1 is the attribute key
    CF=$glidein_config
    if [ "$glidein_config" = "NONE" ]; then
        CF="$PWD/glidein_config"
    fi
    KEY="$1"
    VALUE=`(cat $CF | grep "^$KEY " | tail -n 1 | sed "s/^$KEY //") 2>/dev/null`
    echo "$VALUE"
}

info "Determining extra Singularity capabilities..."

if [ "$glidein_config" != "NONE" ]; then
    ###########################################################
    # import advertise and add_condor_vars_line functions
    if [ "x$add_config_line_source" = "x" ]; then
        export add_config_line_source=`grep '^ADD_CONFIG_LINE_SOURCE ' $glidein_config | awk '{print $2}'`
        export condor_vars_file=`grep -i "^CONDOR_VARS_FILE " $glidein_config | awk '{print $2}'`
    fi

    info "Sourcing $add_config_line_source"
    source $add_config_line_source
fi

# source our helpers
group_dir=$(get_glidein_config_value GLIDECLIENT_GROUP_WORK_DIR)
if [ -e "$group_dir/itb-ospool-lib" ]; then
    source "$group_dir/itb-ospool-lib"
else
    source "$group_dir/ospool-lib"
fi

# can the provided Singularity run .sif images?
if check_singularity_sif_support; then
    # make sure this goes false if we later figure out that
    # singularity is not working correctly
    advertise SINGULARITY_CAN_USE_SIF "HAS_SINGULARITY" "C"
else
    advertise SINGULARITY_CAN_USE_SIF "False" "C"
fi

# can the provided Singularity run registry images?
if check_singularity_registry_support; then
    # make sure this goes false if we later figure out that
    # singularity is not working correctly
    advertise SINGULARITY_CAN_USE_REGISTRY "HAS_SINGULARITY" "C"
else
    advertise SINGULARITY_CAN_USE_REGISTRY "False" "C"
fi



