#!/bin/bash

glidein_config="$1"

function info {
    echo "INFO  " $@ 1>&2
}

function warn {
    echo "WARN  " $@ 1>&2
}

function advertise {
    # atype is the type of the value as defined by GlideinWMS:
    #   I - integer
    #   S - quoted string
    #   C - unquoted string (i.e. Condor keyword or expression)
    key="$1"
    value="$2"
    atype="$3"

    if [ "$glidein_config" != "NONE" ]; then
        add_config_line_safe $key "$value"
        add_condor_vars_line $key "$atype" "-" "+" "Y" "Y" "-"
    fi

    if [ "$atype" = "S" ]; then
        echo "$key = \"$value\""
    else
        echo "$key = $value"
    fi
}


###########################################################
# import add_config_line and add_condor_vars_line functions

add_config_line_source=`grep '^ADD_CONFIG_LINE_SOURCE ' $glidein_config | awk '{print $2}'`
source $add_config_line_source

if [[ $GLIDEIN_Site ]]; then
    glidein_site=$GLIDEIN_Site
else
    glidein_site=$(gconfig_get "GLIDEIN_Site")
fi

set_unexported_condor_config_attribute () {
    # Sets the value of a config knob in the condor config;
    # does not export it as a startd attribute, nor does it export it to the job environment
    # Reference: https://glideinwms.fnal.gov/doc.prd/factory/custom_vars.html
    local name value
    name=$1
    value=$2
    add_config_line "$name" "$value"
    add_condor_vars_line "$name" \
        "C" `# unquoted string (i.e. HTCondor keyword or expression)` \
        "-" `# no default value` \
        "+" `# also use $name for the name of the config knob` \
        "N" `# a value is not required for this attribute` \
        "N" `# do not have the startd publish this to the collector` \
        "-" `# do not export to the user job environment`
}


condor_vars_file=`grep -i "^CONDOR_VARS_FILE " $glidein_config | awk '{print $2}'`

###########################################################
# CVMFS_BASE defaults to /cvmfs but can be overridden in case of for example cvmfsexec
if [[ ! $CVMFS_BASE ]]; then
    CVMFS_BASE="/cvmfs"
fi

# enable job duration and busy stats
add_config_line STATISTICS_TO_PUBLISH_LIST "JobDuration, JobBusyTime"
add_condor_vars_line STATISTICS_TO_PUBLISH_LIST "C" "-" "+" "N" "N" "-"

# black holes, oh my (https://opensciencegrid.atlassian.net/browse/OSPOOL-3)
add_config_line IsBlackHole "IfThenElse(RecentJobDurationAvg is undefined, false, RecentJobDurationCount >= 10 && RecentJobDurationAvg < 180)"
add_condor_vars_line IsBlackHole "C" "-" "+" "N" "Y" "-"

# excessive load, probably due to swapping (https://opensciencegrid.atlassian.net/browse/OSPOOL-2)
add_config_line HasExcessiveLoad "LoadAvg > 2*DetectedCpus + 2"
add_condor_vars_line HasExcessiveLoad "C" "-" "+" "N" "Y" "-"

# out of disk space (https://opensciencegrid.atlassian.net/browse/OSPOOL-4)
# note: Unlike DISK, RESERVED_DISK is in megabytes.
# As of July 2022, the HTCondor manual incorrectly states this is in kilobytes.
# This change was verified by examining the code.
if [[ ! $IS_CONTAINER_PILOT ]]; then
    # Not currently used in container pilots
    add_config_line RESERVED_DISK "3000"
    add_condor_vars_line RESERVED_DISK "C" "-" "+" "N" "N" "-"
fi  # ! $IS_CONTAINER_PILOT

# use df and allocated cores to determine disk allocation (https://opensciencegrid.atlassian.net/browse/OSPOOL-5)
# but only if we think we are not "whole node"
if [[ ! $IS_CONTAINER_PILOT ]]; then
    # This logic is currently not used in container pilots
    allocated_cpus=$(grep -i "^GLIDEIN_CPUS " "$glidein_config" | cut -d ' ' -f 2-)
    total_cpus=$(cat /proc/cpuinfo | egrep "^processor" | wc -l)
    if [[ $allocated_cpus -gt 0 && $total_cpus -gt 0 ]]; then
        allocated_disk=$((100 * $allocated_cpus / $total_cpus))
        if [ "x$allocated_disk" = "x" ]; then
            allocated_disk=1
        fi
        # small slots on large machines, make sure we get at least 1%
        if [[ $allocated_disk -lt 1 ]]; then
            allocated_disk=1
        fi
        if [[ $allocated_cpus -lt 32 ]]; then
            add_config_line GLIDEIN_DISK "$allocated_disk%"
            add_condor_vars_line GLIDEIN_DISK "C" "-" "+" "N" "N" "-"
        fi
    fi
fi  # ! $IS_CONTAINER_PILOT


# Hold jobs if they exceed allocated disk (OSPOOL-26)

# Helper macros
set_unexported_condor_config_attribute  disk_exceeded  '(JobUniverse != 13 && DiskUsage =!= UNDEFINED && DiskUsage > Disk)'
set_unexported_condor_config_attribute  hold_reason_disk_exceeded  'disk usage exceeded request_disk'

# Actual knobs. The following is the equivalent of
# use POLICY : WANT_HOLD_IF(disk_exceeded, $(HOLD_SUBCODE_disk_exceeded:104), $(hold_reason_disk_exceeded))
# since metaknobs are not supported.
set_unexported_condor_config_attribute  PREEMPT  '$(disk_exceeded) || $(PREEMPT:false)'
set_unexported_condor_config_attribute  MAXJOBRETIREMENTTIME  'ifthenelse($(disk_exceeded),-1,$(MAXJOBRETIREMENTTIME:0))'

set_unexported_condor_config_attribute  WANT_SUSPEND  '$(disk_exceeded) =!= true && $(WANT_SUSPEND:false)'

set_unexported_condor_config_attribute  WANT_HOLD  '(JobUniverse != 1 && $(disk_exceeded)) || $(WANT_HOLD:false)'
set_unexported_condor_config_attribute  WANT_HOLD_SUBCODE  'ifThenElse($(disk_exceeded), 104 , $(WANT_HOLD_SUBCODE:UNDEFINED))'
set_unexported_condor_config_attribute  WANT_HOLD_REASON  'ifThenElse($(disk_exceeded), "$(hold_reason_disk_exceeded)", $(WANT_HOLD_REASON:UNDEFINED))'

# End OSPOOL-26


###########################################################
# NAT setups may have an idle timeout where they silently
# drop/forget a connection if they haven't seen packets go
# through.  Send heartbeats more frequently to avoid this.
add_config_line CCB_HEARTBEAT_INTERVAL "120"
add_condor_vars_line CCB_HEARTBEAT_INTERVAL "C" "-" "+" "N" "N" "-"


###########################################################
# debugging GSI
#add_config_line MASTER_DEBUG "D_SECURITY:2"
#add_condor_vars_line MASTER_DEBUG "C" "-" "+" "N" "N" "-"
#add_config_line STARTD_DEBUG "D_SECURITY:2"
#add_condor_vars_line STARTD_DEBUG "C" "-" "+" "N" "N" "-"
#add_config_line STARTER_DEBUG "D_SECURITY:2"
#add_condor_vars_line STARTER_DEBUG "C" "-" "+" "N" "N" "-"


OSDF_FAIL_REASON=""
osdf_plugin_is_ok () {
    local STASH_PLUGIN STASHCP_DEBUG STASHCP_TEST_FILE TIME TIMEOUT
    STASH_PLUGIN="$1"
    STASHCP_DEBUG="-d"
    STASHCP_TEST_FILE="/osgconnect/public/osg/testfile.txt"

    TIMEOUT=$(which timeout 2>/dev/null)
    if [ "x$TIMEOUT" != "x" ]; then
        TIMEOUT="$TIMEOUT 120s"
    fi

    # The bash builtin time is no good because it pollutes
    # stderr with hardcoded real, sys, and user lines.
    TIME=$(which time 2>/dev/null)
    if [ "x$TIME" != "x" ]; then
        # Without --quiet, newer versions of TIME(1)
        # will prepend an extra line to the output
        # if the process exits with a non-zero exit code.
        # Therefore, we use $(tail -1 stashcp-test.time)
        # below to get the runtime of stashcp.
        TIME="$TIME --output=stashcp-test.time --format=%e"
    fi

        # also run a simple test (TODO: make this IGWN-specific)
        rm -f stashcp-test.file
        info "Testing $STASH_PLUGIN $STASHCP_DEBUG $STASHCP_TEST_FILE..."
        if $TIME $TIMEOUT $STASH_PLUGIN $STASHCP_DEBUG $STASHCP_TEST_FILE stashcp-test.file >> stashcp-test.log 2>&1; then
            if [ -f stashcp-test.time ]; then
                info "Succeeded (in $(tail -1 stashcp-test.time)s)!"
            else
                info "Succeeded!"
            fi
            return 0
        else
            if [ "$?" -eq "124" ]; then
                OSDF_FAIL_REASON="Failed (timed out after 120s)!"
            elif [ -f stashcp-test.time ]; then
                OSDF_FAIL_REASON="Failed (in $(tail -1 stashcp-test.time)s)!"
            else
                OSDF_FAIL_REASON="Failed for other reason!"
            fi
            warn "$OSDF_FAIL_REASON stashcp output:"
            while read line; do warn "$line"; done < stashcp-test.log
            return 1
        fi
}

###########################################################
# stashcp 
if [[ ! $IS_CONTAINER_PILOT ]]; then
    # The stashcp executable doesn't come with Condor but we need it for
    # downloading images so we get it from the frontend.
    STASHCP=$PWD/client/stashcp
    chmod 755 $STASHCP

    # TODO Check the STASH_PLUGIN and OSDF_PLUGIN macros defined in the condor config first
    CONDOR_LIBEXEC=$(gconfig_get CONDOR_DIR)/libexec
    if [[ -x $CONDOR_LIBEXEC/osdf_plugin ]]; then
        STASH_PLUGIN=$CONDOR_LIBEXEC/osdf_plugin
    elif [[ -x $CONDOR_LIBEXEC/stash_plugin ]]; then
        STASH_PLUGIN=$CONDOR_LIBEXEC/stash_plugin
    else
        OSDF_FAIL_REASON="OSDF plugin not found in pilot's condor install"
    fi

    if [[ $STASH_PLUGIN ]]; then
        if (echo $glidein_site | grep -E "UW-IT") >/dev/null 2>&1; then
            OSDF_FAIL_REASON="OSDF plugin explicitly disabled at site $glidein_site"
        else
            if osdf_plugin_is_ok "$STASH_PLUGIN"; then
                # osdf_plugin_is_ok sets $OSDF_FAIL_REASON on failure
                add_config_line FILETRANSFER_PLUGINS "\$(FILETRANSFER_PLUGINS),$STASH_PLUGIN"
                add_condor_vars_line FILETRANSFER_PLUGINS "C" "-" "+" "N" "N" "-"
            fi
        fi
    fi
    
    if [[ $OSDF_FAIL_REASON ]]; then
        advertise "OSDF_FAIL_REASON" "$OSDF_FAIL_REASON" "S"
    fi
fi  # ! $IS_CONTAINER_PILOT

##################################################################
# Generate a minimal `STARTER_JOB_ENVIRONMENT`, mostly composed of
# informational variables that are considered safe to always leak to
# the job environment.
#
# Source of OSG_* variables:
#   https://github.com/opensciencegrid/osg-configure/blob/dcd02313500cf113e8a6c27571197b4803295774/scripts/osg-configure#L27
# Removed the following ones that don't appear actively used anymore:
#  OSG_GRID, OSG_APP, OSG_DATA, OSG_SITE_READ, OSG_SITE_WRITE
# Removed $OSG_WN_TMP because any job should use the HTCondor-provided scratch dir.
# Considered and not passed through:
#   LANG
info "Calculating default job environment variables."

if [[ -z $OSG_SITE_NAME ]]; then
    OSG_SITE_NAME=$glidein_site
fi

for envvar in \
     OSG_SITE_NAME \
     OSG_HOSTNAME \
     OSG_SQUID_LOCATION \
     http_proxy \
     https_proxy \
     FTP_PROXY \
     X509_USER_PROXY \
; do

if [ ! -z ${!envvar+x} ]; then
  add_config_line "${envvar}" "${!envvar}"
  add_condor_vars_line "${envvar}" "C" "-" "${envvar}" "N" "N" "+"
fi

done


###########################################################
# Find available volumes and set up bind mounts for Singularity jobs
GLIDEIN_SINGULARITY_BINDPATH=`grep -i "^GLIDEIN_SINGULARITY_BINDPATH " $glidein_config | awk '{print $2}'`
SINGULARITY_BIND_EXPR="/etc/hosts,/etc/localtime"
OLDIFS=$IFS
IFS=' ,'
# shellcheck disable=SC2086
for mntpoint in $GLIDEIN_SINGULARITY_BINDPATH "${CVMFS_BASE}:/cvmfs:ro" /etc/OpenCL/vendors; do
    info "Checking Singularity bind $mntpoint"
    # If we have a source:destination:flags type of bind, just test the source
    mntsource=$(echo "$mntpoint" | cut -d: -f1)
    if [[ -d $mntsource ]]; then
        info "$mntsource found and is a directory; adding to SINGULARITY_BIND_EXPR"
        # but put the whole bind in SINGULARITY_BIND_EXPR
        SINGULARITY_BIND_EXPR="${SINGULARITY_BIND_EXPR},${mntpoint}"
    else
        info "$mntsource not found or not a directory; ignoring"
    fi
done
IFS=$OLDIFS
unset OLDIFS
set_unexported_condor_config_attribute "SINGULARITY_BIND_EXPR" "\"${SINGULARITY_BIND_EXPR}\""
info "SINGULARITY_BIND_EXPR is \"${SINGULARITY_BIND_EXPR}\""

if [[ ! $IS_CONTAINER_PILOT || $CONTAINER_PILOT_USE_JOB_HOOK ]]; then
    # Glideinwms used /srv as the scratch directory, we should do the same
    set_unexported_condor_config_attribute "SINGULARITY_TARGET_DIR" '/srv'
    set_unexported_condor_config_attribute "SINGULARITY_EXTRA_ARGUMENTS" '"--home $_CONDOR_SCRATCH_DIR:/srv"'

    # Have Condor handle using a "default" image
    set_unexported_condor_config_attribute "SINGULARITY_IMAGE_EXPR" '(SingularityImage ?: OSG_DEFAULT_SINGULARITY_IMAGE)'

    # Run all jobs in singularity if we have it
    set_unexported_condor_config_attribute "SINGULARITY_JOB" "(HAS_SINGULARITY?:false)"

    # Condor PID namespace autodetection is broken (TODO add ticket); hard-disable it if we were asked to.
    # I could consolidate these if statements but I'm curious where it's set...
    if [[ $SINGULARITY_DISABLE_PID_NAMESPACES == 1 ]]; then
        info "SINGULARITY_DISABLE_PID_NAMESPACES is set in the environment; disabling PID namespaces"
        set_unexported_condor_config_attribute "SINGULARITY_USE_PID_NAMESPACES" "false"
    elif [[ $(gconfig_get "SINGULARITY_DISABLE_PID_NAMESPACES") == 1 ]]; then
        info "SINGULARITY_DISABLE_PID_NAMESPACES is set in glidein config; disabling PID namespaces"
        set_unexported_condor_config_attribute "SINGULARITY_USE_PID_NAMESPACES" "false"
    else
        info "Leaving SINGULARITY_DISABLE_PID_NAMESPACES at default"
    fi

    add_config_line "OSG_USING_JOB_HOOK" "true"
else
    add_config_line "OSG_USING_JOB_HOOK" "false"
fi  # ! $IS_CONTAINER_PILOT || $CONTAINER_PILOT_USE_JOB_HOOK

# Not a knob -- I am advertising it so I can see it in condor_status
add_condor_vars_line "OSG_USING_JOB_HOOK" "C" "-" "+" "Y" "Y" "-"

###########################################################
# Add prepare hook to do the OSPool-specific transform of
# the Singularity container outside of the glidein default
# image.
if [[ ! $IS_CONTAINER_PILOT || $CONTAINER_PILOT_USE_JOB_HOOK ]]; then
    glidein_group_dir=`grep -i "^GLIDECLIENT_GROUP_WORK_DIR " $glidein_config | awk '{print $2}'`
    for search_path in $glidein_group_dir/{prepare-hook,itb-prepare-hook,itb-prepare-hook-lib}; do
        if [[ -e $search_path ]]; then
            hook_path=$search_path
        fi
    done
    chmod +x "$hook_path"
    if [[ ! -e $hook_path ]]; then  # should not happen
        warn "job hook not found"
        add_config_line "HAS_SINGULARITY" "false"
        add_config_line "SINGULARITY_COMMENT" "Disabled due to missing job hook"
        add_condor_vars_line "SINGULARITY_COMMENT" "S" "-" "+" "Y" "Y" "-"
        add_config_line "OSG_USING_JOB_HOOK" "false"
    else
        # TODO: these can all be replaced with set_unexported_condor_config_attribute
        add_config_line "OSPOOL_HOOK_PREPARE_JOB" "$hook_path"
        add_condor_vars_line "OSPOOL_HOOK_PREPARE_JOB" "C" "-" "OSPOOL_HOOK_PREPARE_JOB" "N" "N" "-"
        add_config_line "STARTER_JOB_HOOK_KEYWORD" "OSPOOL"
        add_condor_vars_line "STARTER_JOB_HOOK_KEYWORD" "C" "-" "STARTER_JOB_HOOK_KEYWORD" "N" "N" "-"
        add_config_line "OSPOOL_HOOK_PREPARE_JOB_TIMEOUT" "900"
        add_condor_vars_line "OSPOOL_HOOK_PREPARE_JOB_TIMEOUT" "C" "-" "OSPOOL_HOOK_PREPARE_JOB_TIMEOUT" "N" "N" "-"
    fi
fi  # ! $IS_CONTAINER_PILOT || $CONTAINER_PILOT_USE_JOB_HOOK

# debugging prepare job hook
if [[ ! $IS_CONTAINER_PILOT || $CONTAINER_PILOT_USE_JOB_HOOK ]]; then
    add_config_line "STARTER_DEBUG" "D_FULLDEBUG:2"
    add_condor_vars_line "STARTER_DEBUG" "C" "-" "STARTER_DEBUG" "N" "N" "-"
fi  # ! $IS_CONTAINER_PILOT || $CONTAINER_PILOT_USE_JOB_HOOK

###########################################################

echo "All done (osgvo-additional-htcondor-config)"

