#!/bin/bash

# Sometimes when glideins get preempted too quickly, a glide_* workdir
# can be left behind. The script checks for such leftovers, and tries
# to clean them up.

cd ..

echo "Checking for leftover glide_* directories in $PWD"

for DIR in $(find . -maxdepth 1 -name glide_\* -user $USER -mtime +2); do

    DIR=$(echo "$DIR" | sed -e 's;^[/.]*;;')
    SIZE=$(du -s --si $DIR | awk '{print $1;}')
    LASTMOD=$(stat --format='%y' $DIR)

    # double check that this is not an active glidein
    if [[ $(find $DIR -maxdepth 1 -name osgvo.test-results.1h.panopticon -mmin -120 -print) ]]; then
        continue
    fi
    
    echo "  Cleanup candidate: $DIR   ($SIZE, $LASTMOD)"

    # just information for now    
    stat $DIR | sed 's/^/      /'
    ls -l $DIR/ | sed 's/^/            /'

done

