#!/bin/bash

if [ "x$1" = "x-classad" ]; then
   echo "PluginVersion = \"0.1\""
   echo "PluginType = \"FileTransfer\""
   echo "SupportedMethods = \"stash\""

   exit 0
fi

FULLSRC=$1
LOC=$2
SRC=$(echo $FULLSRC | cut -d':' -f2-)
. /cvmfs/oasis.opensciencegrid.org/osg/modules/lmod/current/init/bash
module load stashcp/2.1
module load xrootd
stashcp -r -s $SRC -l $LOC > /dev/null 2>&1
