#!/bin/bash
#
# This script is script sources from multiple other scripts.
# Only put functions in here
#
# Assumptions: "glidein_config" has been defined already
#

# global enviroment - make sure apptainer/singularity do not
# fill up $HOME
TARGET_TMP=$(gconfig_get TMP_DIR)
if [ "x$TARGET_TMP" != "x" ]; then
    export APPTAINER_CACHEDIR=${APPTAINER_CACHEDIR-"$TARGET_TMP/apptainer/cache"}
    export APPTAINER_TMPDIR=${APPTAINER_CACHEDIR-"$TARGET_TMP/apptainer/tmp"}
    export SINGULARITY_CACHEDIR="${APPTAINER_CACHEDIR}"
    export SINGULARITY_TMPDIR="${APPTAINER_TMPDIR}"
    mkdir -p $APPTAINER_CACHEDIR $APPTAINER_TMPDIR
fi

function info {
    echo "INFO  $*" 1>&2
}

function my_warn {
    echo "WARN   $*" 1>&2
    export GLIDEIN_VALIDATION_WARNINGS="$@. $GLIDEIN_VALIDATION_WARNINGS"
}

function advertise {
    # atype is the type of the value as defined by GlideinWMS:
    #   I - integer
    #   S - quoted string
    #   C - unquoted string (i.e. Condor keyword or expression)
    key="$1"
    value="$2"
    atype="$3"

    if [ "$glidein_config" != "NONE" ]; then
        gconfig_add_safe $key "$value"
        add_condor_vars_line $key "$atype" "-" "+" "Y" "Y" "-"
    fi

    if [ "$atype" = "S" ]; then
        echo "$key = \"$value\""
    else
        echo "$key = $value"
    fi
}

function check_singularity_overunderlay {
    # some sites have broken singularity overlay/underlay
    # test this by trying to bind pwd to a nonexistent directory
    # in the container
    local has_singularity=$(gconfig_get HAS_SINGULARITY)
    local singularity_path=$(gconfig_get GWMS_SINGULARITY_PATH)
    local default_image=$(gconfig_get SINGULARITY_IMAGES_DICT | sed 's/^default://')

    if [ "x$default_image" = "x" ]; then
        default_image="/cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo-el8:latest/"
    fi

    # singularity is a prereq
    if [[ $has_singularity != "True" ]]; then
        return 0
    fi

    output=$(timeout 60s $singularity_path exec -B $PWD:/doesnotexist $default_image /bin/true 2>&1)
    ret=$?

    if [[ $ret != 0 ]]; then
        # DEBUGGING
        info "Error testing for overlay/underlay; output:"
        info "$output"
        return $ret
    else
        return 0
    fi
}

function check_singularity_overrides {
    GLIDEIN_Entry_Name=$(gconfig_get GLIDEIN_Entry_Name)
    GLIDEIN_Site=$(gconfig_get GLIDEIN_Site)
    # AMNH-HEL - Singularity causes zombie process
    # (https://support.opensciencegrid.org/a/tickets/69708)
    if (echo "$GLIDEIN_Entry_Name" | egrep -i "AMNH-HEL") >/dev/null 2>&1; then
        advertise HAS_SINGULARITY "False" "C"
        advertise SINGULARITY_COMMENT "Disabled due to zombie process problem" "S"
    fi
    if (echo "$GLIDEIN_Site" | egrep -i "SDSC-PRP") >/dev/null 2>&1; then
        advertise HAS_SINGULARITY "False" "C"
        advertise SINGULARITY_COMMENT "Disabled due to singularity setup" "S"
    fi
}

function osdf_download {
    # Use pelican to download a sif file; if the destination does not end in .sif, unpack the sif into the sandbox format
    local dest="$1"
    local src="$2"

    local dest_sif="${dest%.sif}.sif"
    local work_dir=$(gconfig_get GLIDEIN_WORK_DIR)

    # find a pelican client to use
    for PELICAN in $work_dir/condor/usr/bin/pelican /usr/bin/pelican $(which pelican 2>/dev/null); do
        if [ -e $PELICAN ]; then
            break
        fi
    done

    if [ "x$PELICAN" != "x" -a -e $PELICAN ]; then
        rm -rf "$dest" \
            && $PELICAN object get "$src" "$dest_sif"
        ret=$?
    else
        warn "pelican is not available"
        return 255
    fi

    if [[ $ret != 0 ]]; then
        # delete on incomplete download
        rm -f "$dest_sif"
        return $ret
    fi

    if [[ "$dest_sif" != "$dest" ]]; then
        $GWMS_SINGULARITY_PATH build --force --sandbox "$dest" "$dest_sif"
        ret=$?
        rm -f "$dest_sif"
        return $ret
    fi
}

function http_download {
    # Use curl/wget to download a sif file; if the destination does not end in .sif, unpack the sif into the sandbox format
    local dest="$1"
    local src="$2"

    local dest_sif="${dest%.sif}.sif"

    if command -v curl >/dev/null 2>&1; then
        curl --silent --verbose --show-error --fail --location --connect-timeout 30 --speed-limit 1024 -o "$dest_sif" "$src"
        ret=$?
    elif command -v wget >/dev/null 2>&1; then
        wget -nv --timeout=30 --tries=1 -O "$dest_sif" "$src"
        ret=$?
    else
        warn "Neither curl nor wget are available"
        return 255
    fi
    if [[ $ret != 0 ]]; then
        # delete on incomplete download
        rm -f "$dest_sif"
        return $ret
    fi

    if [[ "$dest_sif" != "$dest" ]]; then
        $GWMS_SINGULARITY_PATH build --force --sandbox "$dest" "$dest_sif"
        ret=$?
        rm -f "$dest_sif"
        return $ret
    fi
}


function check_singularity_sif_support {
    # Return 0 if singularity can directly run a .sif file without having to
    # unpack it into a temporary sandbox first, nonzero otherwise.
    #
    # We know this needs setuid Singularity configured to allow loopback
    # devices but there may be other conditions so just test it directly.

    # Grab an alpine image from somewhere; ok to download each time since
    # it's like 3 megs
    local arch=$(uname -m)
    local cvmfs_alpine="/cvmfs/oasis.opensciencegrid.org/osg/projects/OSG-Staff/images/$arch/library__alpine__latest.sif"
    # temporary seperation until we decide on longterm multi-arch hosting
    if [ "X$arch" = "Xx86_64" ]; then
        local static_registry_alpine="docker://ospool-static-registry.osg.chtc.io/alpine:latest"
    else
        local static_registry_alpine="docker://hub.opensciencegrid.org/htc/minimal:0"
    fi
    local work_dir=$(gconfig_get GLIDEIN_WORK_DIR)
    local image_dir="$work_dir/../images"
    local has_singularity=$(gconfig_get HAS_SINGULARITY)
    local singularity_path=$(gconfig_get GWMS_SINGULARITY_PATH)

    # do not allow .sif images on 3.x kernels (OSPOOL-18)
    if (uname -r | egrep '^3\.') >/dev/null 2>&1; then
        return 1
    fi

    # do not allow sif images at Nebraska - the container-in-container is not working
    GLIDEIN_Site=$(gconfig_get GLIDEIN_Site)
    if (echo "$GLIDEIN_Site" | egrep -i "Nebraska") >/dev/null 2>&1; then
        return 1
    fi

    # if singularity is not in the path at this point (detection happens later),
    # we have to assume SIF support
    if ! ($singularity_path --version) >/dev/null 2>&1; then
        info "Singularity missing in the path during SIF detection, assuming SIF download is ok"
        return 0
    fi

    # singularity is a prereq
    if [[ $has_singularity != "True" ]]; then
        return 1
    fi

    # only download once
    if [ ! -e $image_dir/gwms-alpine.sif.log ]; then
        (cp "$cvmfs_alpine" $image_dir/gwms-alpine.sif ||
             timeout 60s $singularity_path pull --force $image_dir/gwms-alpine.sif "$static_registry_alpine" ||
             my_warn "All sources failed - could not create gwms-alpine.sif"
        ) &> $image_dir/gwms-alpine.sif.log
    fi

    # did the download fail
    if [ ! -e $image_dir/gwms-alpine.sif ]; then
        cat "$image_dir/gwms-alpine.sif.log" >&2
        return 1
    fi

    output=$(timeout 60s $singularity_path exec $image_dir/gwms-alpine.sif /bin/true 2>&1)
    ret=$?

    if [[ $ret != 0 ]]; then
        # DEBUGGING
        info "Error testing for SIF support; output:"
        info "$output"
        return $ret
    elif grep -q "temporary sandbox" <<< "$output"; then
        info "Using a SIF created a temporary sandbox"
        return 1
    else
        return 0
    fi
}

function check_singularity_registry_support {
    # Return 0 if singularity can directly run a registry image without having to
    # unpack it into a temporary sandbox first, nonzero otherwise.
    # This also tests building a SIF from a registry image
    #
    local arch=$(uname -m)
    # temporary seperation until we decide on longterm multi-arch hosting
    if [ "X$arch" = "Xx86_64" ]; then
        local static_registry_alpine="docker://ospool-static-registry.osg.chtc.io/alpine:latest"
    else
        local static_registry_alpine="docker://hub.opensciencegrid.org/htc/minimal:0"
    fi
    local has_singularity=$(gconfig_get HAS_SINGULARITY)
    local singularity_path=$(gconfig_get GWMS_SINGULARITY_PATH)

    # singularity is a prereq
    if [[ $has_singularity != "True" ]]; then
        return 1
    fi

    output=$(timeout 60s $singularity_path exec --disable-cache $static_registry_alpine /bin/true 2>&1)
    ret=$?

    if [[ $ret != 0 ]]; then
        # DEBUGGING
        info "Error testing for registry support; output:"
        info "$output"
        return $ret
    elif grep -q "temporary sandbox" <<< "$output"; then
        info "Using a registry created a temporary sandbox"
        return 1
    else
        return 0
    fi
}

function microarch_version {
    # use only /proc/cpuinfo to determine microarchitecture
    # returns an int 1-4 indicating the level
    # v1: all x86-64 CPUs
    # v2: look for sse4_2, popcnt, cx16
    # v3: must also have avx2, fma, bmi1, bmi2, movbe
    # v4: must also have all of the above plus avx512f, avx512dq, avx512cd, avx512bw, avx512vl

    flags=$(grep -m1 '^flags' /proc/cpuinfo)

    if echo "$flags" | grep -qw avx512f && \
       echo "$flags" | grep -qw avx512dq && \
       echo "$flags" | grep -qw avx512cd && \
       echo "$flags" | grep -qw avx512bw && \
       echo "$flags" | grep -qw avx512vl; then
        echo "4"
    elif echo "$flags" | grep -qw avx2 && \
         echo "$flags" | grep -qw bmi2 && \
         echo "$flags" | grep -qw fma; then
        echo "3"
    elif echo "$flags" | grep -qw sse4_2 && \
         echo "$flags" | grep -qw popcnt && \
         echo "$flags" | grep -qw cx16; then
         echo "2"
    else
        echo "1"
    fi
}

