#!/bin/bash

glidein_config="$1"
source $glidein_config

function info {
    echo "INFO  " "$@" 1>&2
}

function warn {
    echo "WARN  " "$@" 1>&2
}


function advertise { 
    # atype is the type of the value as defined by GlideinWMS:
    #   I - integer
    #   S - quoted string
    #   C - unquoted string (i.e. Condor keyword or expression)
    key="$1"
    value="$2"
    atype="$3"

    if [ "$glidein_config" != "NONE" ]; then
        add_config_line_safe "$key" "$value"
        add_condor_vars_line "$key" "$atype" "-" "+" "Y" "Y" "-"
    fi

    if [ "$atype" = "S" ]; then
        echo "$key = \"$value\""
    else
        echo "$key = $value"
    fi
}


info "This is a hello-world script done by Neha Talluri"

if [ true ]; then
        warn "testing the warn function"
fi

# ADD_CONFIG_LINE_SOURCE – Script that can be used to add new attributes to the glidein configuration file
add_config_line_source=`grep '^ADD_CONFIG_LINE_SOURCE ' $glidein_config | awk '{print $2}'`
source $add_config_line_source

# advertises to the condor_startd
advertise "helloworld" true "C"

#add to the glidein config
gconfig_add "helloworld" true
myvar=gconfig_get "helloworld"
print(myvar)
