#!/bin/bash

glidein_config="$1"

function info {
    echo "INFO  " "$@" 1>&2
}

function warn {
    echo "WARN  " "$@" 1>&2
}

function advertise { 
    # atype is the type of the value as defined by GlideinWMS:
    #   I - integer
    #   S - quoted string
    #   C - unquoted string (i.e. Condor keyword or expression)
    key="$1"
    value="$2"
    atype="$3"

    if [ "$glidein_config" != "NONE" ]; then
        add_config_line_safe "$key" "$value"
        add_condor_vars_line "$key" "$atype" "-" "+" "Y" "Y" "-"
    fi

    if [ "$atype" = "S" ]; then
        echo "$key = \"$value\""
    else
        echo "$key = $value"
    fi
}

if [ "$glidein_config" != "NONE" ]; then
    ###########################################################
    # import advertise and add_condor_vars_line functions
    if [ "x$add_config_line_source" = "x" ]; then
        export add_config_line_source=`grep '^ADD_CONFIG_LINE_SOURCE ' $glidein_config | awk '{print $2}'`
        export condor_vars_file=`grep -i "^CONDOR_VARS_FILE " $glidein_config | awk '{print $2}'`
    fi

    add_config_line_source=$PWD/add_config_line.source

    info "Sourcing $add_config_line_source"
    source $add_config_line_source
fi

##############################################################################################################

tracepath -m 1 google.com
tp_error_code=$?

if [ $tp_error_code -eq 0 ]; then
  advertise "HasTracePath" true "C"
  gconfig_add "HasTracePath" true
else
  advertise "HasTracePath" false "C"
  gconfig_add "HasTracePath" false
fi

traceroute -m 1 google.com
tr_error_code=$?

if [ $tr_error_code -eq 0 ]; then
  advertise "HasTraceRoute" true "C"
  gconfig_add "HasTraceRoute" true
else
  advertise "HasTraceRoute" false "C"
  gconfig_add "HasTraceRoute" false
fi
