#!/bin/bash

glidein_config="$1"

function info {
    echo "INFO  " "$@" 1>&2
}

function warn {
    echo "WARN  " "$@" 1>&2
}

function advertise {
    # atype is the type of the value as defined by GlideinWMS:
    #   I - integer
    #   S - quoted string
    #   C - unquoted string (i.e. Condor keyword or expression)
    key="$1"
    value="$2"
    atype="$3"

    if [ "$glidein_config" != "NONE" ]; then
        gconfig_add_safe "$key" "$value"
        add_condor_vars_line "$key" "$atype" "-" "+" "Y" "Y" "-"
    fi

    if [ "$atype" = "S" ]; then
        echo "$key = \"$value\""
    else
        echo "$key = $value"
    fi
}


###########################################################
# import gconfig_add and add_condor_vars_line functions

add_config_line_source=`grep '^ADD_CONFIG_LINE_SOURCE ' $glidein_config | awk '{print $2}'`
source $add_config_line_source

if [[ $GLIDEIN_Site ]]; then
    glidein_site=$GLIDEIN_Site
else
    glidein_site=$(gconfig_get "GLIDEIN_Site")
fi


set_condor_knob () {
    # Sets the value of a config knob in the condor config;
    # does not export it as a startd attribute, nor does it export it to the job environment
    # Reference: https://glideinwms.fnal.gov/doc.prd/factory/custom_vars.html
    local name value
    name=$1
    value=$2
    gconfig_add "$name" "$value"
    add_condor_vars_line "$name" \
        "C" `# unquoted string (i.e. HTCondor keyword or expression)` \
        "-" `# no default value` \
        "+" `# also use $name for the name of the config knob` \
        "N" `# a value is not required for this attribute` \
        "N" `# do not have the startd publish this to the collector` \
        "-" `# do not export to the user job environment`
}


# used indirectly in `add_condor_vars_line`
# shellcheck disable=SC2034
condor_vars_file=$(gconfig_get CONDOR_VARS_FILE)


# In a factory pilot, at the time this script is invoked, the Condor
# installation will be in a directory like
#       main/condor/
if [[ $IS_CONTAINER_PILOT ]]; then
    CONDOR_DIR=/usr
    REAL_CONDOR_DIR=/usr
    CONDOR_LIBEXEC=/usr/libexec/condor
else
    CONDOR_DIR=$(gconfig_get CONDOR_DIR)
    # shellcheck disable=SC2086
    REAL_CONDOR_DIR=$(echo $CONDOR_DIR/condor-*/usr)
    # ^^ the "echo" is needed to expand the glob
    CONDOR_LIBEXEC=$CONDOR_DIR/libexec
fi


OSDF_FAIL_REASON=""
osdf_plugin_is_ok () {
    # Performs tests on the OSDF plugin passed as an argument.
    # Sets $OSDF_FAIL_REASON for a human-readable failure reason, or "" on success.

    local OSDF_PLUGIN OSDF_DEBUG OSDF_TEST_FILE TIME TIMEOUT
    OSDF_PLUGIN="$1"
    OSDF_DEBUG="-d"
    OSDF_TEST_FILE="osdf:///pelicanplatform/test/hello-world.txt"

    TIMEOUT=$(which timeout 2>/dev/null)
    if [ "x$TIMEOUT" != "x" ]; then
        TIMEOUT="$TIMEOUT 120s"
    fi

    # The bash builtin time is no good because it pollutes
    # stderr with hardcoded real, sys, and user lines.
    TIME=$(which time 2>/dev/null)
    if [ "x$TIME" != "x" ]; then
        # Without --quiet, newer versions of TIME(1)
        # will prepend an extra line to the output
        # if the process exits with a non-zero exit code.
        # Therefore, we use $(tail -1 osdf-test.time)
        # below to get the runtime of osdf.
        TIME="$TIME --output=osdf-test.time --format=%e"
    fi

    # also run a simple test (TODO: make this IGWN-specific)
    rm -f osdf-test.file
    info "Testing $OSDF_PLUGIN $OSDF_DEBUG $OSDF_TEST_FILE..."
    if ($TIME $TIMEOUT $OSDF_PLUGIN $OSDF_DEBUG $OSDF_TEST_FILE osdf-test.file) >> osdf-test.log 2>&1; then
        if [ -f osdf-test.time ]; then
            info "Succeeded (in $(tail -1 osdf-test.time)s)!"
        else
            info "Succeeded!"
        fi

        OSDF_PLUGIN_VERSION=$("$OSDF_PLUGIN" -classad | awk '/^(Pelican)?PluginVersion / { print $3; exit }' | tr -d '"' 2>>osdf-test.log)
        if [[ $OSDF_PLUGIN_VERSION ]]; then
            OSDF_FAIL_REASON=""
        else
            # So close!
            OSDF_FAIL_REASON="Failure getting plugin version!"
        fi

        # 7.11.0 is the minimal version we want to use
        if [ "x$OSDF_FAIL_REASON" = "x" ]; then
            if ! (printf '%s\n%s\n' "7.11.0" "$OSDF_PLUGIN_VERSION" | sort --check=quiet --version-sort); then
                OSDF_FAIL_REASON="Plugin is too old ($OSDF_PLUGIN_VERSION)."
            fi
        fi
    else
        if [ "$?" -eq "124" ]; then
            OSDF_FAIL_REASON="Failed (timed out after 120s)!"
        elif [ -f osdf-test.time ]; then
            OSDF_FAIL_REASON="Failed (in $(tail -1 osdf-test.time)s)!"
        else
            OSDF_FAIL_REASON="Failed for other reason!"
        fi
    fi

    if [[ $OSDF_FAIL_REASON ]]; then
        warn "$OSDF_FAIL_REASON osdf output:"
        while read line; do warn "$line"; done < osdf-test.log
        return 1
    fi
}

download_and_extract_pelican () {
    # Download and extract a downloaded Pelican tarball from the given URL and
    # rename the binary to stash_plugin so we can install it as a condor FT
    # plugin.
    local url="$1"

    mkdir -p pelican-tmp/ &&
    curl -LSso pelican-tmp/pelican.tar.gz "$url" &&
    tar -C pelican-tmp/ -xzf pelican-tmp/pelican.tar.gz &&
    (mv -f pelican-tmp/pelican-*/pelican ./stash_plugin || mv -f pelican-tmp/pelican ./stash_plugin) &&
    chmod +x stash_plugin
}


# set_condor_knob REDIRECT_FILETRANSFER_PLUGIN_STDERR_TO_STDOUT 'TRUE'
# set_condor_knob LOG_FILETRANSFER_PLUGIN_STDOUT_ON_FAILURE 'D_ALWAYS'
# ^^ apparently these two are already the default
set_condor_knob LOG_FILETRANSFER_PLUGIN_STDOUT_ON_SUCCESS 'D_ALWAYS'

# Allow downloading Pelican by setting DOWNLOAD_PELICAN_VERSION in the
# environment.  If set to an X.Y.Z string with a matching vX.Y.Z tag in GitHub,
# it will download the Pelican binary from the release artifacts of that tag.
#
# If set to "condor", it will use what's in the Condor tarball.  (This can be
# used to override a non-Condor default.)
# Handle itb and production differently
GLIDECLIENT_Group=$(gconfig_get GLIDECLIENT_Group)
if (echo "$GLIDECLIENT_Group" | grep itb) >/dev/null 2>&1; then
    # ITB
    # Have these two be different to test two versions in parallel
    # or compare a new version with a 'known good' version
    rand=$(( RANDOM % 3 ))  # use the same random number
    case $rand in
        0) DEFAULT_DOWNLOAD_PELICAN_VERSION=7.22.1      ;; # known good
        1) DEFAULT_DOWNLOAD_PELICAN_VERSION=7.23.0-rc.7 ;; # testing 1
        *) DEFAULT_DOWNLOAD_PELICAN_VERSION=7.24.0-rc.0 ;; # testing 2
    esac
else
    # Production
    DEFAULT_DOWNLOAD_PELICAN_VERSION=condor
fi

if [[ ! $DOWNLOAD_PELICAN_VERSION ]]; then
    DOWNLOAD_PELICAN_VERSION=$(gconfig_get DOWNLOAD_PELICAN_VERSION)
    if [[ ! $DOWNLOAD_PELICAN_VERSION ]]; then
        DOWNLOAD_PELICAN_VERSION=$DEFAULT_DOWNLOAD_PELICAN_VERSION
    fi
fi


advertise "Ran_Pelican_Setup" 1 C


###########################################################
# Test and add the stash/osdf plugin
# It comes with condor, or we might be asked to download it.

# Find the Stash/OSDF plugin; set OSDF_PLUGIN to its current location.
# The plugin will be tested later.
if [[ $DOWNLOAD_PELICAN_VERSION && $DOWNLOAD_PELICAN_VERSION != condor ]]; then
    # If this variable is set, and not set to "condor", download that
    # version of Pelican and ignore the version from the HTCondor tarball.

    pelican_arch=$(arch)
    if [[ $pelican_arch == aarch64 ]]; then
        pelican_arch=arm64
    fi
    url=https://github.com/PelicanPlatform/pelican/releases/download/v${DOWNLOAD_PELICAN_VERSION}/pelican_Linux_${pelican_arch}.tar.gz
    # Pelican >= v7.9.0 tarballs will have the binary in a subdirectory of the
    # tarball; < 7.9.0 have it at the top level.
    _out=$(download_and_extract_pelican "$url" 2>&1); ret=$?
    if [[ $ret != 0 || ! -f stash_plugin || ! -x stash_plugin ]]; then
        OSDF_FAIL_REASON="Couldn't download and install requested Pelican version ($DOWNLOAD_PELICAN_VERSION)"
        add_to_debug "Pelican install output: $_out"
    else
        OSDF_PLUGIN=$(pwd -P)/stash_plugin
        advertise "DOWNLOAD_PELICAN_VERSION" "$DOWNLOAD_PELICAN_VERSION" "S"
    fi
    rm -rf "pelican-tmp/" &>/dev/null
else
    # Not asked to download a specific Pelican version, or specifically
    # asked to use what's in the HTCondor tarball.
    # Find the stash/osdf plugin in the HTCondor installation.
    if [[ -x $CONDOR_LIBEXEC/osdf_plugin ]]; then
        # forward compat
        OSDF_PLUGIN=$CONDOR_LIBEXEC/osdf_plugin
    elif [[ -x $CONDOR_LIBEXEC/stash_plugin ]]; then
        OSDF_PLUGIN=$CONDOR_LIBEXEC/stash_plugin
    else
        OSDF_FAIL_REASON="Stash/OSDF plugin not found in pilot's condor install"
    fi
fi

# Check if the site is excluded, and if not, test the plugin
if [[ $OSDF_PLUGIN ]]; then

    # Check if the site is in pelican-exceptions.csv - the file will be placed
    # in some gwms group specific directory, so search for it
    PCSV=$(find . -name pelican-exceptions.csv 2>/dev/null | head -n1)
    if [[ $PCSV != "" ]]; then
        info "Found exceptions file in $PCSV"
        while IFS=, read -r site block_percent reason; do
            [[ $site =~ ^# ]] && continue  # Skip comments
            if [[ "$glidein_site" == "$site" ]]; then
                # roll is a random number between 1 and 100 - compare this
                # with the provided block percentage (for example, if we roll
                # a 73 on a site with 90%, that will result in a block)
                roll=$((RANDOM % 100 + 1))
                if [ $roll -le $block_percent ]; then
                    OSDF_FAIL_REASON="OSDF suspended at $site ($block_percent%): $reason"
                    break
                fi
            fi
        done < $PCSV
    fi

    # If the site is not in the exceptions list, test the plugin
    if [[ ! $OSDF_FAIL_REASON ]]; then
        if osdf_plugin_is_ok "$OSDF_PLUGIN"; then
            # osdf_plugin_is_ok sets $OSDF_FAIL_REASON
            gconfig_add FILETRANSFER_PLUGINS "\$(FILETRANSFER_PLUGINS),$OSDF_PLUGIN"
            add_condor_vars_line FILETRANSFER_PLUGINS "C" "-" "+" "N" "N" "-"
            set_condor_knob STASH_PLUGIN "$OSDF_PLUGIN"
            set_condor_knob OSDF_PLUGIN "$OSDF_PLUGIN"
        fi
    fi
fi

if [[ $OSDF_FAIL_REASON ]]; then
    advertise "OSDF_FAIL_REASON" "$OSDF_FAIL_REASON" "S"
    # Turn off the condor config's STASH_PLUGIN and OSDF_PLUGIN in case they're set
    set_condor_knob STASH_PLUGIN "/bin/false"
    set_condor_knob OSDF_PLUGIN "/bin/false"
fi


